Feature: Add sponser viewset
pythonkr/pyconkr-api-v2 pull request #14
Opened 2023-02-05 13:44 UTC by oleveloper

### 목표
* Sponsor 페이지의 Insert 기능 구현

### 작업내용
* ViewSet 추가

### 유의사항
* 리뷰어는 `PyConKR-2023`을 지정 해 주세요.
* 작업한 내용을 상세하게 작성해주세요.

2023-02-05 14:48 UTC, hanlee55 requested changes
주석에 대한 확인을 부탁드립니다.

Ps. 수고하셨습니다! 감사합니다.

2023-02-05 14:48 UTC, hanlee55 commented on sponsor/viewsets.py
> +    permission_classes = [IsAuthenticatedOrReadOnly]  # 로그인된 사용자에게만 허용
`IsAuthenticatedOrReadOnly` 에 대하여 '로그인된 사용자에게**만** 허용' 이란 주석이 설명이 부족한 것 같습니다.
제가 알기로는 해당 권한은 인증되지 않은 사용자에 대해서는 GET 등의 요청에 대한 접근을 허용 하는 것으로 알고 있습니다.

자료: [https://www.django-rest-framework.org/api-guide/permissions/#isauthenticatedorreadonly](https://www.django-rest-framework.org/api-guide/permissions/#isauthenticatedorreadonly)

2023-02-05 15:53 UTC, golony6449 commented
아하 Viewset과 라우터도 적용을 해주셨군요 :-) 

저도 자세히는 몰라서.. 
`노가다 성이 있지만, APIView으로 만들고 나중에 Viewset으로 옮겨봐야겠다` 하고 혼자 생각하고 있었는데
고생 많으셨습니다. ㅠㅠ

2023-02-06 12:42 UTC, golony6449 commented on pyconkr/urls.py
> +    path("sponsors/", include(sponsor.routers.get_router().urls)),
👍

2023-02-06 12:57 UTC, golony6449 commented on sponsor/viewsets.py
> +    permission_classes = [IsAuthenticatedOrReadOnly]  # 로그인된 사용자에게만 허용
@hanlee55 님이 코멘트 주신 것처럼 주석 내용 수정이 필요해 보이네요.

해당 `permission`은 로그인한 사용자에게는 모든 작업을 그렇지 않으면 조회를 허용하는 케이스입니다.

2023-02-06 13:10 UTC, golony6449 commented on sponsor/viewsets.py
> +    permission_classes = [IsAuthenticatedOrReadOnly]  # 로그인된 사용자에게만 허용
@oleveloper
퍼미션에 대한 수정도 필요할 것 같아요~!

`ModelViewSet`을 상속받는다는 가정 하에, 지금의 퍼미션에서는 아래의 이슈가 예상됩니다.

1. CFS 기능은 로그인 적용 이전에 배포될 예정이어서, 아무도 POST를 할 수 없습니다.
2. 제출된 후원사 내용을 누구나 조회할 수 있습니다. 
3. 일단 로그인만 되면, DB 저장된 레코드를 추정해, 다른 사용자의 데이터도 수정/삭제할 수 있습니다.

지금 DRF에서 `본인의 데이터만 조회할 수 있음` 퍼미션은 없어서,
1. 로직에 해당 내용을 포함시키거나,
2. 커스텀 퍼미션을 만들거나

하는 방법이 있을 것 같아요.

* 참고자료: https://stackoverflow.com/questions/72691826/djnago-rest-framework-how-to-allow-only-update-user-own-content-only

이건 같이 작업해보실까요 ㅎㅎ

2023-02-06 15:55 UTC, hanlee55 approved these changes
@oleveloper @golony6449 코드 확인하면서 많이 배웠습니다!

수고하셨습니다 :)

2023-02-06 15:55 UTC, hanlee55 commented on sponsor/permissions.py
> +        return obj.manager_id == request.user or obj.creator == request.user
말씀 주신 커스텀 퍼미션 이군요! 👍

2023-02-06 15:55 UTC, hanlee55 commented on sponsor/permissions.py
> +        return obj.manager_id == request.user or obj.creator == request.user
관리자가 `creator`와 `manager` 둘 다 있었네요 👍

2023-02-06 15:55 UTC, hanlee55 commented on sponsor/viewsets.py
> +from sponsor.serializers import SponsorListSerializer, SponsorSerializer
👍

2023-02-06 15:55 UTC, hanlee55 commented on sponsor/viewsets.py
> +        serializer = (
와! 이렇게 작성이 가능하군요. 👍

2023-02-07 11:28 UTC, oleveloper commented on sponsor/viewsets.py
> +    permission_classes = [IsAuthenticatedOrReadOnly]  # 로그인된 사용자에게만 허용
꼼꼼한 리뷰 감사드립니다. 생각지 못한 부분이네요. 
@hanlee55 @golony6449 두 분께서 말씀하신 바와 같이, 인증되지 않은 사용자에 대해 Read only 권한만 부여합니다. 
이 부분은 API 이름을 통해 명확하게 기능을 판단할 수 있으므로 혼동을 야기시킬 수 있는 본 주석을 제거하도록 하겠습니다.

2023-02-07 12:37 UTC, oleveloper commented on sponsor/permissions.py
> +        return obj.manager_id == request.user or obj.creator == request.user
값을 바꾸지 않는 methods 일 때, 또는 매니저 또는 작성자가 접근할 때에만 Permission이 부여되는 커스텀 퍼미션이군요. 확인했습니다.

2023-02-07 16:12 UTC, Linho1150 commented
코드 잘 읽었습니다 :)
익숙하던 view를 떠나서 viewset으로 코드를 읽어보니 정말 재미난 부분이 많네요!
오늘도 덕분에 좋은 기능 배워갑니다! 고생하셨습니다! 감사합니다 😊

2023-02-07 16:14 UTC, Linho1150 commented on sponsor/viewsets.py
> +            if self.check_owner_permission(request, sponsor_data)
단순한 호기심이 있다면 🤔
해당 코드에서 not을 사용하지 않고 else로 처리한건 관용적으로 사용하는 부분이 있는지 궁금하네요 :)

2023-02-07 16:14 UTC, Linho1150 approved these changes

2023-02-08 10:02 UTC, merged