의존성 추가: django-constance
pythonkr/pyconkr-api-v2 pull request #24
Opened 2023-02-22 15:49 UTC by golony6449

### 목표
* 설정값 관리를 위한 저장소가 필요합니다. (Slack 알림 채널, Secret 등)

### 작업내용
* django-constance를 의존성에 추가합니다.

### 유의사항
* 리뷰어는 `PyConKR-2023`을 지정 해 주세요.
* 작업한 내용을 상세하게 작성해주세요.

2023-02-23 04:43 UTC, oleveloper approved these changes

2023-02-23 12:51 UTC, pers0n4 requested changes

2023-02-23 12:51 UTC, pers0n4 commented on pyconkr/settings.py
> +CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
이 부분이 single quote네요

2023-02-24 13:01 UTC, golony6449 commented on pyconkr/settings.py
> +CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
@pers0n4 감사합니다 :-)

2023-02-24 13:02 UTC, merged